name: Close Pull Request

# only trigger on pull request closed events
on:
  release:
    types: [published]
  workflow_run:
    workflows: ["Label PR on appVersion Change"]
    types: 
      - completed
    paths:
      - deploy/helm/Chart.yaml

jobs:
  merge_job:
    # this job will only run if the PR has been merged
    if:  (!contains(github.event.pull_request.labels.*.name, 'app-version-changed')) 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      if:  github.event.inputs.ref == ''
      with:
          fetch-depth: 0
    - name: Run a one-line script
      run: echo Hello, world!