# only trigger on pull request closed events
on:
  release:
    types: [published]
  repository_dispatch:
    types: [my-event]
    paths:
      - deploy/helm/Chart.yaml

jobs:
  merge_job:
    # this job will only run if the PR has been merged
    if:  github.event.client_payload.action != 'do-not-publish' 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      if:  github.event.inputs.ref == ''
      with:
          fetch-depth: 0
    - name: Run a one-line script
      run: echo Hello, world!