# only trigger on pull request closed events
name: Publish
on:
  repository_dispatch:
    types: [publish-chart]
    paths:
      - deploy/helm/Chart.yaml

jobs:
  merge_job:
    # this job will only run if the PR has been merged
    if:  github.event.client_payload.action == 'publish-chart' 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      if:  github.event.client_payload.tag != ''
      with:
          ref: ${{ github.event.client_payload.tag }}
          fetch-depth: 0
    - uses: actions/checkout@v2
      if:  github.event.client_payload.tag == ''
      with:
          fetch-depth: 0
    - name: Run a one-line script
      run: echo Hello, world!