name: Close Pull Request

# only trigger on pull request closed events
on:
  pull_request:
    types: [ closed ]

jobs:
  ready_for_publish:
    permissions:
      pull-requests: read
      checks: write
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true 
    runs-on: ubuntu-latest
    steps:
      - uses: danielchabr/pr-labels-checker@v3
        id: checkLabel
        with:
          hasSome: app-version-changed
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!