name: Label PR on appVersion Change

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - Chart.yaml
      

jobs:
  check-appversion-change:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Check for appVersion change
        id: check-appversion
        run: |
          app_version_changed=$(git diff ${{ github.before }} ${{ github.event.after }}  Chart.yaml | grep -E '^\+\s*appVersion:' | sed 's/^\+\s*appVersion: //')
          if [ -n "$app_version_changed" ]; then
            echo "::set-output name=app_version_changed::true"
          else
            echo "::set-output name=app_version_changed::false"
          fi

          version_changed=$(git diff ${{ github.before }} ${{ github.event.after }} Chart.yaml | grep -E '^\+\s*version:' | sed 's/^\+\s*version: //')
          if [ -n "$version_changed" ]; then
            echo "::set-output name=version_changed::true"
          else
            echo "::set-output name=version_changed::false"
          fi
          

      - name: add label one
        if: steps.check-appversion.outputs.app_version_changed == 'true'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: app-version-changed

      - name: add label one
        if: steps.check-appversion.outputs.version_changed == 'true'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: chart-version-changed
       
