name: Label PR on appVersion Change

on:
  pull_request_target:
    types:
      - closed
    paths:
      - deploy/helm/Chart.yaml
      
jobs:
  check-appversion-change:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 

      - name: Get latest tag
        id: latest_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 | sed 's/v//')
          echo "::set-output name=tag::$latest_tag"
          
      - name: Read Chart.yaml appVersion
        id: chart_version
        run: |
          app_version=$(grep -E '^appVersion:' deploy/helm/Chart.yaml | awk '{print $2}')
          echo "::set-output name=app_version::$app_version"

      - name: add app-version-changed label
        if: ${{ steps.latest_tag.outputs.tag != steps.chart_version.outputs.app_version }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: app-version-changed

      - name: Repository Dispatch Label PR
        if: ${{ steps.latest_tag.outputs.tag != steps.chart_version.outputs.app_version }}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: my-event
          client-payload: '{"action": "do-not-publish"}'
